export const PAINT_BRANDS = [
  "Abteilung 502",
  "AK 3rd Generation",
  "AK 3rd Generation - AFV",
  "AK 3rd Generation - Air",
  "AK 3rd Generation - Figure",
  "AK Interactive",
  "AK Interactive Air Series",
  "AK Real Colors",
  "Akan",
  "Alclad II",
  "Ammo by Mig Jimenez",
  "Andrea Color",
  "Citadel",
  "Colourcoats",
  "Floquil",
  "Hataka Hobby Blue Line",
  "Hataka Hobby Orange Line",
  "Hataka Hobby Red Line",
  "Humbrol",
  "ICM",
  "Italeri Acrylic Paint",
  "Lifecolor",
  "MIG Productions",
  "Mission Models",
  "Model Master",
  "Mr. Aqueous Hobby Color",
  "Mr. Weathering Color",
  "Mr. Weathering Paste",
  "Mr.COLOR",
  "MR.Paint",
  "Pactra",
  "Revell Aqua Color",
  "Revell Color",
  "SMS",
  "Tamiya",
  "Tamiya Color Lacquer Paint",
  "Tamiya Paint Markers",
  "Tamiya Polycarb Marker",
  "Testors",
  "The Army Painter",
  "Vallejo",
  "Vallejo Diorama Effects",
  "Vallejo Game Air",
  "Vallejo Game Color",
  "Vallejo Hobby Paint",
  "Vallejo Mecha Colors",
  "Vallejo Metal Color",
  "Vallejo Model Air",
  "Vallejo Model Color",
  "Vallejo Model Wash",
  "Vallejo Panzer Aces",
  "Vallejo Pigments",
  "Vallejo Premium Airbrush Colors",
  "Vallejo Surface Primer",
  "Vallejo Weathering Effects",
  "Van Gogh",
  "Winsor & Newton",
  "XtraColor",
  "XtraCrylix",
  "Zero Paints",
  "Zvezda",
] as const;

export type PaintBrand = typeof PAINT_BRANDS[number];
